### ISSUE TITLE
Wildcard/extension only validation

### ISSUE THREAD

**Issue by lelu0** [orkhanahmadov/laravel-zip-validator#2]
Adding wildcard validation by looking only for files with a certain extension will be useful. Currently, I have a case where I want to validate if any DDS file is present in ZIP, so I'd love to do something like this:

`new ZipContent('*.dds')`

Cheers and thanks for the great validator.

**Comment by orkhanahmadov** [comment]
@lelu0, I like the idea. I'll update the package soon, will add the wildcard validation option.

**Comment by nilskretschmer** [comment]
Hey,

I would like to integrate this nice package. I need to check one/multiple ZIP Uploads against a list of whitelisted file extensions - So I need to reject the upload if there are files within the Zip with a "forbidden" extension. Is this already possible? If not where should I start to add it this functionality to the lib?

Thank you in advance!

**Comment by orkhanahmadov** [comment]
Thanks again @lelu0 and @nilskretschmer. Honestly, I forgot about this request previously... Sorry...

I just added the wildcard matching feature with #7 and released [1.11.0](https://github.com/orkhanahmadov/laravel-zip-validator/releases/tag/1.11.0).

With the new version, you can use wildcard matching like:
- `*.pdf`
- `some_folder/file_prefix_*.txt`

You can find more information and additional matching pattern options on the [README](https://github.com/orkhanahmadov/laravel-zip-validator/blob/master/README.md#wildcard-filename-matching).

**Comment by orkhanahmadov** [comment]
@nilskretschmer I think what you need with the "forbidden" extension check is something different and currently not supported by this package...

Also, I think checking against file extensions to decide if it is "forbidden" or not is probably not a good idea in general. Since file extensions can be easily changed and faked. Users can upload executable files in a zip archive and give it a `.txt` extension. I believe, for your need, you might need a different solution where you unzip the file and check against MIME types or something a bit safer than just a file extension check.

From the beginning, the goal of this package was more like accepting a zip upload from a user and expecting certain files or file/folder patterns in it. Like, you ask a user to upload an html theme as a zip and you expect that the archive should contain `index.css`, and `styles.css` files.

But if you have a solution in mind, please feel free to open a PR.
